### ISSUE TITLE
[Bug] Path parameter also being shown in request body params

### ISSUE THREAD

**Issue by emalamela** [Wolox/dictum#4]
The bug is displayed here:

![screenshot from 2017-05-10 11-43-38](https://cloud.githubusercontent.com/assets/7926479/25904585/0d3795b4-3576-11e7-8545-adcc3b1ff939.png)
I believe this is redundant.

**Comment by alebian** [comment]
This comes from the way to are using the gem. You can customize the configuration a bit more to filter certain keys or to hide the path parameters completely.
